export function carl() {
    return {
        name: 'Carloman Randolph'
        , title: 'Who killed Julian'
        , details:[
            {label:'Occupation',value:'Stable hand'}
            , {label:'Means',value:'Morgenstern, a cesspit and a wheelbarrow'}
            , {label:'Motive', value:'The death of a friend, and Julian used him to train Morgenstern to hate Corwin'}
            , {label:'Traits:',value:''}
            ,{label:"\u2727",value:'Passing resemblance to Corwin'}
            ,{label:"\u2727",value:'Affinity for animals, horses in particular'}
            ,{label:"\u2727",value:'Holds grudges'}
            ,{label:"\u2727",value:'Proud'}
            ,{label:"\u2727",value:'Powerful physique'}
            ,{label:"\u2727",value:'Better with animals than with people'}
        ]
        , download:'./assets/files/carl.docx'
        , slot:'6-3'
        , gm:'Matthew'
        , desc:{
            blurb:`“Prince Julian? Yeah. I hate him. I really, really do. I suppose it’s not a secret. I mean… there’s not much to like, is there? He’s aloof, arrogant, cruel, prissy, cowardly, hell, I could go on and on about his many, many flaws. Look, I get it, nobody’s perfect, I’m no saint myself, but that guy? I could tell you stories, man. I really could.
            You see, I’m a stable hand… that’s not a stable boy, thank you very much, I take pride in my work. Or I used to do. Anyway…
            It’s hard work. Horses need a lot of maintenance, they need feeding and grooming, and their stabling cleared and cleaned out; you have no idea how much manure a single horse produces, I tell you. You can just keep shoveling all day and never be done. But it’s okay, it’s part of the job, and horses are generally nice to be around. They’re honest creatures, you know? Treat them right and you’ll get exactly what you give. They’re like these big, dumb, emotional, soulful mirrors, really. It’s hard to explain, if you don’t know horses. The important part to take away is that you have to treat them right, and you have to love them.
            And Julian? Well, our Princely Prince of Porcelain Perfection, he doesn’t love his horses. I don’t think he ever loved anything, except perhaps the sound of his own voice and his image in the mirror. He’s a selfish, narcissist prick. And a right arsehole, too. You know he calls me “Randy”? That is, if he even remembers my name. Otherwise it’s “hey, boy” or “you there”. The very best I can get from him is “Charlie”, which still isn’t my name, thank you very much. 
            He treats his horses as tools and status symbols. Sure, he loves his public image as the majestic prince on the white horse, but you’ll never catch him actually caring for them. He’ll never unsaddle a horse, or feed it a treat, or even touch one on the neck to soothe it when it’s riled. He. Doesn’t. Care.
            If it weren’t for me, his entire stable would just be full of wretches that would only see the light of day if he wants to parade them around, they’d never be brought out to graze in the pasture, or exercised, or groomed, or shoed. They’d just stand in their tiny stables, knee high in their own filth, suffering from laminitis or hoofrot of what have you. I’m the one who cares about them, cares for them, and Julian takes the credit for it. 
            And that would still be okay. I could deal with that. Even if I couldn’t take them out to graze, even if I had to spend all day shoveling piss and manure out of their stables, it would be fine. Horses are great, and I loved horses. Love horses. I would happily do this until the end of my days if it weren’t for that monster Morgenstern, and what that bastard son of Oberon did to it. What he made me do.
            He took a good horse, a fine creature, and he did … things to it. Unnatural things. Gruesome things. Made it bigger, stronger, made it vicious. Made it a predator. That monstrous thing eats meat, did you know that? It thinks it’s a hunting animal. It’s all I can every day to keep it from attacking the other horses, to keep it from taking a bite out of the other stables hands, or myself for that matter. It sweats like a steam bath, and it never, ever tires. And the smell… oh, the smell. Let me tell you about the smell.
            Horse dung isn’t so bad. It takes a little getting used to, sure, but anyone who deals with horses will tell you that you barely even notice it anymore when you do. But that … thing? It’s like dogshit, cooked in blood, and mixed with vitriol. It gets everywhere. It makes my eyes tear, it makes me gag. It’s absolutely bloody disgusting, and it shits. All. The. Fucking. Time. You can’t even use it as manure. Tried it, once, one a patch of grass away from the pasture, and everything there died. Couldn’t have done more damage if I’d salted the earth. Nothing will grow there anymore.
            We had to dig a separate cesspit just for getting rid of Morgenstern’s shit. It’s far away from the stables, and it reeks to high heaven. I have to push cartload after cartload there every single day, and it’s like the bowels of hell in there. 
            We had to have the stables rebuilt, just to house that monster. Parts of the building are now more heavily reinforced than the castle ramparts, and it still tries to kick its way out to get to the other horses. I fear for my life, every day, when I have to go feed that beast, and when I have to clean up after it. It’s a nightmare. A living nightmare. Oh, and of course, I can’t feed it just any old meat, of course. No, his lordship Prince Polished insists that I feed it venison. Veal at the very least. Prime cuts of meat, too. There are families in the city that have to survive on soup and prayers, but this monster gets the best of the best, and mind that you don’t get seen taking some leftovers home! Last year, he caught one of the younger hands taking some of the scraps with him that Morgenstern had left on the floor. I was basically offal. I swear to Unicorn, Julian had the boy brought up on theft and poaching charges. You know what they do to poachers caught on royal grounds? … Yeah, exactly. Lucky for him, the kid only received the sentence for theft, on grounds of it being his first offence. Well, I say lucky, but I still think it’s pretty harsh to have a fifteen year old’s right hand cut off because he picked up some meat from the dirt. You should have seen the prince beaming, too. Like he was some kind of hero, having brought justice to the world. Arsehole.
            But Carloman, I hear you ask, isn’t he the fabled Guardian of Arden? Surely, there must be some merit to the man? Oh, don’t get me started. Do you really think he keeps the great forest safe? All by himself? Do you think he’s the one who trains the dogs, the hawks, everything, and that he patrols the dark and far of the woods? His rangers do all the work. He just takes the credit. And those fables hunts he leads? He leads from the rear, if you know what I mean. He’ll have someone rustle up and wear down some poor buck or swine, and when the poor creature is too tired to run anymore, then the great Guardian rides up and puts the poor thing out of his misery. He’d never actually face something that might actually fight back. But nobody ever talks about that, of course. No one would dare accuse the Lord Protector of the Realm with cowardice. I only know because Christobal got ratface drunk last year and spilled the truth. Of course, he’s not here to anymore to tell about it. Christobal suffered a terrible hunting accident a few weeks later. According to the prince, there was nothing he could have done to save him when that buck gored my friend, and Julian had to risk  life and limb himself to kill the animal afterwards.
            Funny, that. Never did see a buck that gored someone from behind. Never saw one leaves such wounds behind, either. They almost looked like sword wounds.
            Oh well. No sense in questioning the prince’s version of events, now is there?
            So no, I don’t have many reasons to like prince Julian. But do you want to know why I hate him? Why I really, really hate him? 
            It’s Morgenstern. Before Julian turned it into …whatever it is that it’s now, because I’ll be damned if I call it a horse, he wanted it trained. Makes sense, that. But do you know how he wanted it trained? He wanted it to go berserk whenever prince Corwin was around. He wanted it to hate Corwin as much as he did. So what he did was dress me up in Corwin’s clothes, and then he sent me into the pen to hurt it. Kick it, cut it. Make it suffer. Do you know how hard that was? For someone like me, to purposefully hurt an innocent animal like that, to be so cruel, so vindictive, that the poor horse went completely mad with fright and anger every time it smelled or saw anything that looked like prince Corwin… or me? 
            
            And now, every day, I have to go in there and face this gruesome beast, a beast that has every reason to hate me, and I have to see what I helped it become. I have to see what I did to it, and how it turned one of the world’s finest creations into the worst, most pitiful, most dreadful thing I’ve seen, all because of a sorry excuse for a human being’s petty sibling rivalry. I hate it. I hate myself, for this. But most of all, I hate Julian. Oh, how I despise Julian.
            I’ve dreamed about ending him, you know. About killing him. I know exactly how I’d do it, too. You see, to keep Morgenstern docile enough to clean out his stable, we basically have to flood it with ether. I’m guessing that if it’s good enough to slow that thing down, it’s good enough for Julian. I’d lure him into the stable with some kind of excuse… I don’t know, maybe I’d tell him I found the king’s missing ruby necklace in the hay, or something. That thing has been missing for ages, right? So then, when eager, greedy Julian goes in there to check for himself, I’d lock the door and flood the stable, enough to make them both drowsy. I know how quick Morgenstern recovers, so I’d wait until it’s almost up, and then I’d toss a wasp’s nest in there with them. There’s a nice big one hanging on a branch in the apple orchard, that would do fine. 
            I’m hoping the wasps will get a few good stings in on the woozy Prince of the Porcelain Throne. Of course, even if they really can’t hurt the Morgenstern, all the angry buzzing bugs are pretty much going to panic the accursed beast, and if there’s one thing you don’t want to do, it’s to be in a stable with a panicking warhorse. It’ll crush you, bite you, trample you, and then shit and piss on you when you go down. It happens on occasion, and the results are never pretty.
            When that’s done and over with, I’d flood the stables with ether again, this time all the way so ‘Stern is incapacitated, and I can fish out whatever’s left of that tin can bastard prince. If he’s really unlucky, that armor of his is actually functional enough to keep him alive… because he’d still be battered, beaten and broken. And at that point, I’d be of the intent to wheel him in of the big acid-proof wheelbarrows right up to and into Morgenstern’s cesspit. 
            And I’d drop the barrow right on top of him, for good measure.
            All that’s left then is to seal the pit up, go home, and have a smoke and a beer, and remember my friend Christobal while that rotten bastard Julian sinks deep into the vile shitpuddle that his monster created, beaten, broken, alone and in the dark. Yeah.
            It’d never happen, I know. Who am I to raise a hand to a Prince? I’m just a lowly stable hand. It’s not my place. It’s nice to dream, though.
            It’s nice to dream.”`            
            , summary: 'Story'
            , pic:'./assets/img/carl.png'
        }
    };
};
